spring:
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://ep-cold-mountain-aux08ghy-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}a

app:
  base-currency: USD